bezier = overshoot, 0.05, 0.9, 0.1, 1.1
animation = workspaces, 1, 8, default
animation = workspaces, 1, 8, default, slidefade 20%
#animation = windows, 1, 10, default, slide
animation = fade, 0 
#animation = windows, 1, 8, default, popin 50%

